README update and some cleanups.
ros2/rcl_logging pull request #120
Opened 2024-08-27 17:06 UTC by fujitatomoya

2024-08-27 17:06 UTC, fujitatomoya commented on rcl_logging_noop/CMakeLists.txt
> +  src/rcl_logging_noop.cpp
this aligns with rcl_logging_spdlog directory tree.

2024-08-27 17:07 UTC, fujitatomoya reviewed
@clalancette @wjwwood minor update mostly docs, can you take a look?

2024-08-27 17:07 UTC, fujitatomoya commented on rcl_logging_spdlog/README.md
> -    - [rcl_logging_spdlog/visibility_control.h](include/rcl_logging_spdlog/visibility_control.h)
this file does not exist.

2024-08-27 17:20 UTC, clalancette requested changes

2024-09-04 16:58 UTC, fujitatomoya commented on rcl_logging_noop/CMakeLists.txt
> +  src/rcl_logging_noop.cpp
https://github.com/ros2/rcl_logging/pull/120/commits/7df68baf786810a7d57d4436bc5a37f60a296468 fixes.

2024-09-04 16:59 UTC, fujitatomoya commented
@clalancette requesting another review on this.

2024-09-04 17:00 UTC, fujitatomoya commented
Pulls: ros2/rcl_logging#120
Gist: https://gist.githubusercontent.com/fujitatomoya/38f6efeffacfd7206e46612c78a45217/raw/276f1d6e84baef70790959dc1b765419f16697f0/ros2.repos
BUILD args:  --packages-up-to rcl_logging_noop rcl_logging_spdlog
TEST args:  --packages-select rcl_logging_noop rcl_logging_spdlog
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14512
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21787)](http://ci.ros2.org/job/ci_linux/21787/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16059)](http://ci.ros2.org/job/ci_linux-aarch64/16059/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1290)](http://ci.ros2.org/job/ci_linux-rhel/1290/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22486)](http://ci.ros2.org/job/ci_windows/22486/)

2024-09-04 17:11 UTC, clalancette approved these changes
Looks good to me with green CI.

2024-09-05 08:33 UTC, ahcorde approved these changes

2024-09-05 08:33 UTC, merged